### ISSUE TITLE
Request to Integrate with GraphQLSwift group

### ISSUE THREAD

**Issue by NeedleInAJayStack** [GraphQLSwift/SwiftDataLoader#8]
Hi @kimdv, I've started using your package and added some functionality, like timer-based batching and NIO v2 support. I was wondering if I could pull it over into a project on the [GraphQLSwift](https://github.com/GraphQLSwift) organization. Of course, I'd give you kudos in the readme! Just wanted to check and make sure you're okay with that.

Thanks!

**Comment by kimdv** [comment]
Hi @NeedleInAJayStack ! 
I was actually thinking about to reach out to the GraphQLSwift to donate this project. 

Should we transfer the repository or will you add is as a package to GraphQLSwift/GraphQL ?

**Comment by NeedleInAJayStack** [comment]
@kimdv Awesome, thanks! I think we ought to keep it separate from GraphQLSwift/GraphQL (in keeping with the canonical JavaScript implementation), so transferring the repo would be great. Let me know if I can help at all.

**Comment by kimdv** [comment]
I have invited you to this repo. 
Then you can transfer it. I don't have permission to create public repos in GraphQLSwift org. 

Thanks!

**Comment by NeedleInAJayStack** [comment]
Hmm, I don't think I can transfer the Repo except as an owner. I'll just copy it over into a repo on that project. Let me know if that's unacceptable and you'd like to transfer it - in that case I can reach out to get you GraphQLSwift membership.

**Comment by kimdv** [comment]
Hm okay. 
If I can get membership of GraphQLSwift, then I will transfer. Need access to create public repo. 
You can just remove me afterwards again.

**Comment by NeedleInAJayStack** [comment]
Ok, sounds good. Hey @paulofaria, could you make @kimdv a member of GraphQLSwift so he can transfer this DataLoader repo to the organization?

**Comment by paulofaria** [comment]
@NeedleInAJayStack done!

**Comment by kimdv** [comment]
Aaaand it is moved! 

Thanks and congratulations 🚀🚀

**Comment by NeedleInAJayStack** [comment]
Awesome!! Thanks so much!
